### PR TITLE
Add Increment A-Inductor

### LINKED ISSUE #10: Creation of Components

### PR DESCRIPTION
**Pull request by sevenseasofbri**

### CODE REVIEW

**Review by hughjazzman — APPROVED** [review]
Perhaps JavaDoc to be added, but other than that LGTM.

**Comment by hughjazzman** [comment]
#10 Inductor done.

**Comment by sevenseasofbri** [comment]
> Perhaps JavaDoc to be added, but other than that LGTM.

Ohh right I forgot. I'll do it.

**Review by PraveenElango — APPROVED** [review]
Looks good to me!

**Comment by hughjazzman** [comment]
No need to link the issue #10 yet, else it will automatically close it when you merge. Can link when the last component is done.

**Pull request merged**
